name: release-containers
on:
  release:
    types:
      - "published"

jobs:
  publish-container-images:
    name: publish-container-images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base-image:
          - scratch
          - erlang
          - erlang-slim
          - erlang-alpine
          - elixir
          - elixir-slim
          - elixir-alpine
          - node
          - node-slim
          - node-alpine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: lpil
          password: ${{ secrets.CONTAINER_REGISTRY_PERSONAL_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build version and tags
        id: versions
        run: |
          # Strip git ref prefix from version
          V_VERSION=$(echo "${{ github.ref }}" | sed -e 's|.*/\(.*\)|\1|')

          # Strip `v` prefix from version
          BARE_VERSION=$(echo "$V_VERSION" | sed -e 's|^v/\(.*\)|\1|')

          # Build version with platform
          PLATFORM_VERSION=$BARE_VERSION-${{ matrix.base-image }}

          # Build container tag
          TAG=ghcr.io/${{ github.repository }}:$PLATFORM_VERSION

          echo "v_version=$V_VERSION" >> $GITHUB_OUTPUT
          echo "bare_version=$BARE_VERSION" >> $GITHUB_OUTPUT
          echo "platform_version=$PLATFORM_VERSION" >> $GITHUB_OUTPUT
          echo "container_tag=$TAG" >> $GITHUB_OUTPUT

      - name: Download Rakun archives from GitHub release
        run: |
          VERSION=${{ steps.versions.outputs.v_version }}

          AMD_URL=https://github.com/${{ github.repository }}/releases/download/$VERSION/rakun-$VERSION-x86_64-unknown-linux-musl.tar.gz
          ARM_URL=https://github.com/${{ github.repository }}/releases/download/$VERSION/rakun-$VERSION-aarch64-unknown-linux-musl.tar.gz

          echo Downloading amd $AMD_URL
          curl -Lo rakun-amd.tar.gz $AMD_URL

          echo Downloading arm $ARM_URL
          curl -Lo rakun-arm.tar.gz $ARM_URL

      - name: Unpack Rakun binary from archive
        run: |
          tar xf rakun-amd.tar.gz
          mv rakun rakun-amd64

          tar xf rakun-arm.tar.gz
          mv rakun rakun-arm64

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: containers/${{ matrix.base-image }}.dockerfile
          push: true
          tags: ${{ steps.versions.outputs.container_tag }}
          labels: |
            org.opencontainers.image.title=rakun
            org.opencontainers.image.url=https://rakun.run
            org.opencontainers.image.source=https://github.com/rakun-lang/rakun
            org.opencontainers.image.version=${{ steps.versions.outputs.platform_version }}
            org.opencontainers.image.licenses=Apache-2.0
